# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
# cache: cocoapods
podfile: Example/Podfile
before_install:
- pod --version
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/tvOS\ example.xcworkspace -scheme tvOS\ example -sdk appletvsimulator9.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

